name: Cypress Tests in Development Environment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Asegúrate de usar la versión correcta de Node.js

      - name: Install Dependencies
        working-directory: Cliente  # Ajusta esta ruta según tu estructura
        run: npm install  # o yarn install o pnpm install

      - name: Start development server
        working-directory: Cliente
        run: npm run dev &  # Ejecuta el servidor en segundo plano

      - name: Wait for server to start
        run: npx wait-on http://localhost:5173  # Ajusta la URL y el puerto según tu configuración

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev  # Este comando también puede ser necesario si `wait-on` no funciona como espera
          wait-on: 'http://localhost:5173'  # Espera que el servidor de desarrollo esté disponible antes de ejecutar las pruebas
          browser: chrome
