name: Run Vitest Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Paso 2: Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Paso 3: Instalar dependencias en la carpeta Cliente
      - name: Install dependencies
        working-directory: ./Cliente
        run: npm install

      # Paso 4: Ejecutar pruebas con Vitest en la carpeta Cliente
      - name: Run Vitest tests
        working-directory: ./Cliente
        run: npm run test
