name: Cypress Tests with Dependency and Artifact Caching

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies in Cliente
        working-directory: Cliente
        run: npm install

      - name: Build the Project with Vite in Cliente
        working-directory: Cliente
        run: npm run build

      - name: List all files in Cliente after build
        run: ls -R Cliente  # List all files in the Cliente directory for debugging

      - name: Save dist folder
        uses: actions/upload-artifact@v4
        with:
          name: dist
          if-no-files-found: error
          path: Cliente/dist  # Reference the correct output directory for Vite

  cypress-run:
    runs-on: ubuntu-22.04
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download the dist folder
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: Cliente/dist

      - name: Start Server and Run Cypress
        working-directory: Cliente
        uses: cypress-io/github-action@v6
        with:
          start: npm run preview  # Use preview mode to serve the Vite app
          wait-on: "http://localhost:4173"  # Default Vite preview port; adjust if necessary
          browser: chrome
