name: Cypress Tests with Dependency and Artifact Caching

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        working-directory: Cliente
        run: npm install

      - name: Build Application
        working-directory: Cliente
        run: npm run build

      - name: Save build folder
        uses: actions/upload-artifact@v4
        with:
          name: build
          if-no-files-found: error
          path: Cliente/dist  # Adjusted path to the Vite build output

  cypress-run:
    runs-on: ubuntu-22.04
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download the build folder
        uses: actions/download-artifact@v4
        with:
          name: build
          path: Cliente/dist

      - name: Start Preview Server
        working-directory: Cliente
        run: npm run preview &
        
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run preview
          wait-on: "http://localhost:4173"  # Adjust this if using a custom port
          browser: chrome
